configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stainless-bruce-hill%2Fbruce-test-api-2dabda7da091abd85fcb74ba27bc425f773b4fc19d2b6f2e422ee0307da00d91.yml
openapi_spec_hash: 3f2557511acbe6858b73ef85233fcdb4
config_hash: 01fb212f8fad80e2c795fe848b6e6207
