configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stainless-bruce-hill%2Fbruce-test-api-1f6397fc9d8e9b8f0ae8dd8587a8d32142ad3c748c0afc12d0dfbc14b8a159b8.yml
openapi_spec_hash: c946e79eebe7e7f347302da873dbe978
config_hash: 6d6e2aad137b11a9f922fa2eebd2d292
