configured_endpoints: 1
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stainless-bruce-hill%2Fbruce-test-api-7434c4b2b6415aade9078748ea4adedbbb16bfe2b0f7eb576781de07142e1c7b.yml
openapi_spec_hash: 677fc09482e3a8da0097a6af64f8af4b
config_hash: bcc6c5ca97573550d75ff1d42e832f6c
